# Application
spring.application.name=recipe-review

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE}

# application.properties

# Configure DevTools
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# Environment-specific properties
spring.profiles.active=dev

# JWT Configuration
jwt.access.secret=${JWT_ACCESS_SECRET}
jwt.refresh.secret=${JWT_REFRESH_SECRET}
jwt.access.expiration=15
jwt.refresh.expiration=7

# CORS Configuration
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000}

# YouTube API
youtube.api.key=${YOUTUBE_API_KEY}

# Bean Configuration
spring.main.allow-bean-definition-overriding=true